### ISSUE TITLE
Add the ability to block user if the IP doesn't match

### ISSUE THREAD

**Issue by RisedSky** [Elikill58/IpManager#4]

**Comment by Elikill58** [comment]
If the IP doesn't match with what ?

**Comment by RisedSky** [comment]
The last one, I mean.
You connect to the server, your IP is logged in a db / json file.

If you connect again and the IP doesn't match, you are kick until the IP match again with the saved IP.

Can be used in online-mode=false easily.
Obviously the admin can delete the stored IP

**Comment by Elikill58** [comment]
What about people who change from wifi to 4G ? Or just their network OP change their IP because of box reboot or something

**Comment by RisedSky** [comment]
@Elikill58 the IP change only if you stop your box 24 hours, which won't happen (unless for some reason), the user just need to send a message to the owner of the server to add the IP in the list.

You can store more IP if needed, for home internet / 4G or so.
This doesn't limit to only 1 IP, but can of course limit to 1.
It depends on the owner of the server :)

**Comment by Elikill58** [comment]
Yes but when we can know that we have to :
- Store the IP
- Kick for wrong IP
- Change actual IP to new one

**Comment by RisedSky** [comment]
> Yes but when we can know that we have to :
> 
> * Store the IP
> * Kick for wrong IP
> * Change actual IP to new one

First connection => store the IP
Second connection with a new IP => kick the user and notify the owner of the server that a new IP tried to connect to the user account
If the owner add the new IP => 2 IPs are whitelist on the user account, and so on...
You can add muiltiple IP whitelist to the user, as simple like that

**Comment by Elikill58** [comment]
I don't agree with that. It can create issue with people that doesn't ask for something, and we don't should wait for server mod. That's clearly a bad idea.

**Comment by RisedSky** [comment]
Maybe, you can just add a checkbox to enable/disable this, can be disabled by default, this can be very useful for online-mode=false servers.. and prevent others people to login and do whatever they want on the account of the server admin

**Comment by RisedSky** [comment]
Sad that you close it as it can be very interesting and researched by people..

**Comment by Elikill58** [comment]
I should close it as not planned, but maybe someone will have an idea like this, but without be a possible issue for legit people
