### ISSUE TITLE
[Request/Suggestion] Server's IP

### ISSUE THREAD

**Issue by joex92** [Elikill58/IpManager#5]
It may sound a bit weird, but it would be useful if the plugin could check what's the server's public IP...
for example, if a server's IP is dynamic, and the IP changes, from the server console you could run something like `/getserverip` or something like that... and then share the new IP (on chat, if the server's using a discord chat link it could be useful)...

**Comment by Elikill58** [comment]
A dynamic server IP could not really work as, by définition, a server should have a static one. If it's host at you home, the IP could only change when you restart your router. Also, even with own things, in general you have option to disable the dynamic behavior.
Can you explain more why it should be added, what should do when the IP chance and why looses performance to check for an IP that should NOT change ?

**Comment by Elikill58** [comment]
Nothing to do ~ Closed as not planned as I don't see usefulness in this proposition
